export const SAVE_USER_ID = 'SAVE_USER_ID'

export const LOGIN = 'LOGIN'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const LOST_PASSWORD = 'LOST_PASSWORD'
export const LOST_PASSWORD_ERROR = 'LOST_PASSWORD_ERROR'

export const OCCURRENCE = 'OCCURRENCE'
export const OCCURRENCE_ERROR = 'OCCURRENCE_ERROR'
export const OCCURRENCE_UPDATE = 'OCCURRENCE_UPDATE'
export const OCCURRENCE_UPDATE_ERROR = 'OCCURRENCE_UPDATE_ERROR'
export const CLEAR_OCCURRENCE = 'CLEAR_OCCURRENCE'
